package com.tm.dao;

public enum DaoType {

	USER, PROJECT, USER_PROJECT, MODULE, ISSUE, ISSUE_COMMENT, ISSUE_ATTACHMENT, ISSUE_HISTORY,
	ISSUE_SUBSCRIBE, NOTIFICATION, NOTIFICATION_VARIABLE, RELEASE;
}
