Create table TM_USER_INFO (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	USER_ID VARCHAR(15) NOT NULL UNIQUE,
	USER_PASS VARCHAR(15) NOT NULL,
	USER_TYPE VARCHAR(20) NOT NULL,
	USER_NAME VARCHAR(50) NOT NULL,
	USER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
	USER_PHONE VARCHAR(20),
	USER_GROUP_ID VARCHAR(15),
	USER_IMAGE BLOB,
	DT_CREATED TIMESTAMP NOT NULL,
	DT_MODIFIED TIMESTAMP,
	VISIBLE BOOLEAN NOT NULL
);
Create table TM_PROJECT (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	PROJ_NAME VARCHAR(50) NOT NULL,
	PROJ_DESC VARCHAR(1000) NOT NULL,
	PROJ_OWNER BIGINT NOT NULL,
	DT_CREATED TIMESTAMP NOT NULL,
	DT_MODIFIED TIMESTAMP,
	VISIBLE BOOLEAN NOT NULL,
	FOREIGN KEY(PROJ_OWNER) REFERENCES TM_USER_INFO(ID)
);